WebApplication6/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication6.Controllers
{
    public class AdminController : Controller
    {
        database_Access_Layer.db dblayer = new database_Access_Layer.db();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Index(FormCollection fc)
        {
            int res = dblayer.Admin_Login(fc["adminid"], fc["password"]);
            if (res == 1)
            {
                // TempData["msg"] = "login successfully";
                return RedirectToAction("FileUpload", "Account");
            }
            else
            {
                TempData["msg"] = "Admin id or password is wrong";
            }
            return View();
        }
    }
}

WebApplication6/Controllers/SearchController.cs
using WebApplication6.Models;
using WebApplication6.Dapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;


namespace WebApplication6.Controllers
{
    public class SearchController : Controller
    {
        private SqlConnection con;
        private void Dbconnection()
        {
            string constr = ConfigurationManager.ConnectionStrings["dbcon"].ToString();
            con = new SqlConnection(constr);
        }
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult FileDetails()
        {
            List<FileDetailsModel> DetList = GetFileList();
            return PartialView("FileDetails", DetList);
        }

        private List<FileDetailsModel> GetFileList()
        {
            List<FileDetailsModel> DetList = new List<FileDetailsModel>();

            Dbconnection();
            con.Open();
            DetList = SqlMapper.Query<FileDetailsModel>
            (con, "GetFileDetails", commandType: CommandType.StoredProcedure).ToList();
            con.Close();
            return DetList;
        }

        public JsonResult GetSearchingData(string SearchBy, string SearchValue)
        {
            List<FileDetailsModel> detlist = new List<FileDetailsModel>();
            if (SearchBy == "ID")
            {
                try
                {
                    int Id = Convert.ToInt32(SearchValue);
                    detlist = detlist.Where(x => x.Id == Id || SearchValue == null).ToList();
                }
                catch (FormatException)
                {
                    Console.WriteLine("{0} Is Not A ID ", SearchValue);
                }
                return Json(detlist, JsonRequestBehavior.AllowGet);
            }
            else
            {
                detlist = detlist.Where(x => x.EbookName.StartsWith(SearchValue) || SearchValue == null).ToList();
                return Json(detlist, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <title>BookYard</title>

    <link rel="stylesheet" href=@Url.Content("/Content/css/bootstrap.min.css")>
    <link rel="stylesheet" href=@Url.Content("/Content/css/font-awesome.min.css")>

    <!-- Main css -->
    <link rel="stylesheet" href=@Url.Content("/Content/css/style.css")>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

</head>
<body>

    <!-- PRE LOADER -->

    <div class="preloader">
        <div class="sk-spinner sk-spinner-wordpress">
            <span class="sk-inner-circle"></span>
        </div>
    </div>

    <!-- Navigation section  -->

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                </button>
                <a href="@Url.Action("FileDetails","Home")" class="navbar-brand"><i class="fa fa-magnet"></i></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "FileDetails", "Home")</li>
                    <li>@Html.ActionLink("Search Ebooks", "Search", "Home")</li>
                    <li>@Html.ActionLink("Login", "Index", "Admin")</li>
                </ul>
            </div>

        </div>
    </div>

    <!-- Home Section -->

    <section id="home">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <h2><b>BookYard</b></h2><h3> Download Books</h3>
                    <hr>
                </div>
            </div>
        </div>
    </section>

   <div>
       @RenderBody();
   </div>

    <!-- Footer Section -->

    <footer>
        <div class="container">
            <div class="row">

                <div class="col-md-3 col-sm-3">
                    <i class="fa fa-magnet"></i>
                </div>
                
                <div class="col-md-3 col-sm-3">
                        <div class="footer-copyright">
                            <p>© 2018 <a href="https://bookyard.niyatimpatel.co.uk/"> BookYard </a> by <a href="https://niyatipatel.co.uk/">Niyati Patel</a></p>
                        </div>
                    </div>              


                <div class="col-md-6 col-sm-6">
                    <ul class="social-icon">
                        <li><a href="https://www.linkedin.com/in/niyati-patel-16122b15a" class="fa fa-linkedin"></a></li>
                        <li><a href="https://github.com/niyatiap" class="fa fa-github"></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>


    <!-- SCRIPTS -->
    <script src=@Url.Content("/Content/js/jquery.js")></script>
    <script src=@Url.Content("/Content/js/bootstrap.min.js")></script>
    <script src=@Url.Content("/Content/js/custom.js")></script> 

</body>
</html>